// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = {
    cf: {
      bare: {
        bg: '#C87533',
        txt: 'white'
      },
      gold: {
        bg: 'goldenrod',
        txt: 'white'
      },
      'Ni/Au': {
        bg: 'whitesmoke',
        txt: 'black'
      },
      hasl: {
        bg: 'silver',
        txt: 'black'
      }
    },
    sm: {
      red: {
        bg: 'darkred',
        txt: 'white'
      },
      orange: {
        bg: 'darkorange',
        txt: 'black'
      },
      yellow: {
        bg: '#FFFF66',
        txt: 'black'
      },
      green: {
        bg: 'darkgreen',
        txt: 'white'
      },
      blue: {
        bg: 'navy',
        txt: 'white'
      },
      purple: {
        bg: 'indigo',
        txt: 'white'
      },
      black: {
        bg: 'black',
        txt: 'white'
      },
      white: {
        bg: 'white',
        txt: 'black'
      }
    },
    ss: {
      red: {
        bg: 'red',
        txt: 'white'
      },
      yellow: {
        bg: 'yellow',
        txt: 'black'
      },
      green: {
        bg: 'green',
        txt: 'white'
      },
      blue: {
        bg: 'blue',
        txt: 'white'
      },
      black: {
        bg: 'black',
        txt: 'white'
      },
      white: {
        bg: 'white',
        txt: 'black'
      }
    }
  };

}).call(this);
