// Generated by CoffeeScript 1.9.3
(function() {
  var _, layerOpts, reBOTTOM, reMASK, rePASTE, reSILK, reTOP;

  layerOpts = require('./layer-options');

  _ = require('lodash');

  reTOP = /top/i;

  reBOTTOM = /bottom/i;

  reSILK = /(silk)|(ss)/i;

  reMASK = /(soldermask)|(sm)/i;

  rePASTE = /(paste)|(sp)|(pm)/i;

  module.exports = function(name) {
    var i, len, len1, opt, ref, ref1, ref2, ref3, type;
    type = '';
    for (i = 0, len1 = layerOpts.length; i < len1; i++) {
      opt = layerOpts[i];
      if (opt.match.test(name)) {
        return opt.val;
      }
    }
    name = name.split('.')[0];
    if (len = (ref = name.match(reTOP)) != null ? (ref1 = ref[0]) != null ? ref1.length : void 0 : void 0) {
      type = 't';
    } else if (len = (ref2 = name.match(reBOTTOM)) != null ? (ref3 = ref2[0]) != null ? ref3.length : void 0 : void 0) {
      type = 'b';
    }
    if (reSILK.test(name)) {
      type += 'ss';
    } else if (reMASK.test(name)) {
      type += 'sm';
    } else if (rePASTE.test(name)) {
      type += 'sp';
    } else if (name.length === len) {
      type += 'cu';
    }
    if (!_.find(layerOpts, {
      val: type
    })) {
      type = 'drw';
    }
    return type;
  };

}).call(this);
